// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdLvZKeuMdCN2SQXAA2pwVrROeBOgWsnE',
    appId: '1:214953140762:web:8a2fc1e0a79f58924767a3',
    messagingSenderId: '214953140762',
    projectId: 'tanya-mama',
    authDomain: 'tanya-mama.firebaseapp.com',
    storageBucket: 'tanya-mama.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNpXVVAs6mWLcsXt1EnAEaHkFOLI7w9-Q',
    appId: '1:214953140762:android:2be63faa5a531dc44767a3',
    messagingSenderId: '214953140762',
    projectId: 'tanya-mama',
    storageBucket: 'tanya-mama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66M8n8wuuiC1r5Clt9TwUPNNfnZ9WsfY',
    appId: '1:214953140762:ios:bd981a311fd07a304767a3',
    messagingSenderId: '214953140762',
    projectId: 'tanya-mama',
    storageBucket: 'tanya-mama.appspot.com',
    iosClientId: '214953140762-q7fce9n20du2est5pnu3a8qq4lhf0n6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTanyaMama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66M8n8wuuiC1r5Clt9TwUPNNfnZ9WsfY',
    appId: '1:214953140762:ios:bd981a311fd07a304767a3',
    messagingSenderId: '214953140762',
    projectId: 'tanya-mama',
    storageBucket: 'tanya-mama.appspot.com',
    iosClientId: '214953140762-q7fce9n20du2est5pnu3a8qq4lhf0n6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTanyaMama',
  );
}
